INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Jose', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Martha', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Andres', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Martin', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Pedro', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Agustin', 'Guerrero', 'tita@gmail.com', '2019-02-27' , '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Luis', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Cesar', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Omar', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Lupita', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Andrea', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Fernanda', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Luis', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Cesar', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Omar', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Lupita', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Andrea', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Fernanda', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Luis', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Cesar', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Omar', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Lupita', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Andrea', 'Luna', 'jLuna@gmail.com', '2020-10-15', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Fernanda', 'Guerrero', 'tita@gmail.com', '2019-02-27', '');

